### ISSUE TITLE
[UAT] Test average of visits LS means

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/tern.mmrm#107]
UAT the new option `average_emmeans` in`fit_mmrm()` which allows to estimate least square means for averages of visits.

To do:
- [x] Use pre-release branch on enableR (see Dinakar's instructions)
- [x] See `?fit_mmrm` for description of the `average_emmeans` and check if that is clear
- [x] Play around with the argument and results and see if that works

**Comment by danielinteractive** [comment]
@shajoezhu fyi

**Comment by edelarua** [comment]
The `average_emmeans` argument works fine and is described well in the documentation. 

A more concise error message could be added for the case when the given visit levels to be averaged are not present in the dataset if this is a potential concern.

**Comment by danielinteractive** [comment]
Thank you @edelarua !
