### ISSUE TITLE
[UAT] Test fitting of rank-deficient models

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/tern.mmrm#108]
UAT the option `accept_singular` in `fit_mmrm()` which allows to estimate rank-deficient models (similar as `lm()` and `gls()` do) by omitting singular coefficients.

To do:
- [x] Use pre-release branch on enableR (see Dinakar's instructions)
- [x] See `?fit_mmrm` for description of the `accept_singular` and check if that is clear
- [ ] Play around with the argument and results and see if that works - will need very small data sets, or artificially introduced collinear columns in the formula, to see the effect.

**Comment by danielinteractive** [comment]
@shajoezhu fyi

**Comment by edelarua** [comment]
The `accept_singular` argument is documented well and works correctly - when a singular design matrix is found the function returns an error if `accept_singular == FALSE` and reduces to full rank when `accept_singular == TRUE`.

**Comment by danielinteractive** [comment]
Thanks @edelarua !
