### ISSUE TITLE
[UAT] Test visualization of covariance matrix

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/tern.mmrm#112]
UAT the new function `g_covariance()`.

To do:
- [x] Use pre-release branch on enableR (see Dinakar's instructions)
- [x] See `?g_covariance` for description and check if that is clear
- [ ] Play around with the function and see if that works and makes sense

**Comment by danielinteractive** [comment]
@shajoezhu fyi

**Comment by edelarua** [comment]
The function works well and produces correct output. 

Suggestions:
- Use a more descriptive argument name for `string`
- Include a clearer description for `string` argument - description says "see details" but no details are included in the documentation.
