### ISSUE TITLE
[UAT] Test the new MMRM forest plot

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/tern.mmrm#113]
UAT the new MMRM forest plot.

To do:
- [x] Use pre-release branch on enableR (see Dinakar's instructions)
- [x] See `?tabulate_mmrm_subgroups` and `?extract_mmrm_subgroups` for descriptions and check if those are clear
- [ ] Play around with the functions and see if they work, also in combination with `tern::g_forest()`
	- [ ] Note that I am aware that default arguments from `tern::g_forest()` don't look good, however I feel at this stage it is easier to just let the user modify the arguments (i.e. not use log scale, make the vertical line at 0, etc.)

**Comment by danielinteractive** [comment]
@shajoezhu fyi

**Comment by edelarua** [comment]
Both functions work great on their own and with `g_forest`! Documentation is good for `tabulate_mmrm_subgroups`.

Suggestions for `extract_mmrm_subgroups`:
- typo in documentation: "arm, along a list" should be "arm, along with a list"
- Add more detailed description for argument `groups_lists` & add an example that uses this argument
