### ISSUE TITLE
[tern.mmrm] Create forest plot functions for MMRM subgroup analyses

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/tern.mmrm#13]
To do:

- [x] design doc
  - [x] Adjustments to `fit_mmrm()` / `get_mmrm_lsmeans()`
  	- [x] save the `averages_emmeans` list in the object
  	- [x] add the `weights_emmeans` chosen for LS means in the object
  - [x] LS means computations
      - [x] go via separate MMRM fits to compute the LS means for the subgroups
      - [x] works for factor variables used as such
      - [x] works for overlapping combination of factor levels
	  - [x] works for single visit
	  - [x] works for average of visits
  - [x] Extraction function
  - [x] Formatted analysis function
  - [x] Table creating function
- [x] create functions
- [ ] add to TLG-C

--
Original feedback:

FSTG01 layout example from GDSR as follow, with the following note of modification

* Please replace the column heading “Subgroup” with “Baseline Risk Factor”, remove the “Category” column and display the Category headings directly underneath the Baseline Risk Factor heading, as in FSTG01. Also, replace the first row heading, “Overall”, with “All Patients”, consistent with FSTG01
* By default present all summary statistics shown in the mockup. Allow the option for presenting p-value for each mean difference to the right of the 95% CI.  

![image](https://user-images.githubusercontent.com/91914821/140618877-c135e1db-2d59-4332-8b11-ee9ee74d272c.png)

Summary table can be obtained from `fit_mmrm`. 

Provenance: 
```
Creator: anajens
```

**Comment by danielinteractive** [comment]
@shajoezhu as discussed this one could be interesting

**Comment by danielinteractive** [comment]
@juliadedic1 this is the task, please let @shajoezhu if this is high priority for upcoming release (or not)

**Comment by shajoezhu** [comment]
Hi @danielinteractive , thanks for the heads up, this template is very similar to the  AEG_01_OPH  template, https://github.com/insightsengineering/sme-tasks/issues/281

which is currently blocked by this issue https://github.com/Roche/rtables/issues/341

**Comment by danielinteractive** [comment]
@shajoezhu I think this one could be done without rtables but just using the forest plot tools we use also for the other forest plots? (`g_forest` if I remember correctly)

**Comment by danielinteractive** [comment]
Hi @shajoezhu and @juliadedic1 ,

I am currently blocked on this one - Basically the instructions in the FSTG03 template in the GDSR are not specific enough. I only realized this now after I tried out one (of many possible) way (fitted a single MMRM and then tried to extract LS means for subgroups) and realized that it does not work. 

Can you please help me find SAS scripts from study teams (can share by email e.g.) that produced this forest plot? 
I tried to search on our internal github but nothing came up. Also the GDSR does not contain template SAS scripts and I am not sure if there is any for this output.

Thanks a lot!
