### ISSUE TITLE
Debug warnings from graph functions on GRAN devel

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/tern.mmrm#134]
To do:

- [x] Log into Rosalind - alternatively just do this on BEE
	- [x] Run `ml R/dev`
	- [x] load `tern.mmrm` package
- [x] run the tests in https://github.com/insightsengineering/tern.mmrm/blob/main/tests/testthat/test-g_mmrm.R
- [x] reproduce below warnings in tests
- [x] debug what is the problem:
	- [x] most likely we just need to use other functions to avoid deprecation warnings

<img width="811" alt="image" src="https://user-images.githubusercontent.com/1071227/201941466-ec0fac1e-ce1e-46e6-8e3d-929f4adf1d5e.png">

**Comment by arkadiuszbeer** [comment]
It is also reproducible on bee server.

**Comment by juliadedic1** [comment]
@danielinteractive I am not getting these messages when running on BEE R version 4.1.1. All the tests seem to pass except this one in screenshot due to not having the package for `get_version`. 
![image](https://user-images.githubusercontent.com/99106549/205716386-ef6d516a-46ee-4155-80b2-4177785a1409.png)

Is this what we are expecting now?

**Comment by danielinteractive** [comment]
@juliadedic1 sorry I think I forgot to include an important step above, I think we need to install `tern.mmrm` from the `main` branch using `staged.dependencies`, I guess that is how @arkadiuszbeer did it?

**Comment by arkadiuszbeer** [comment]
@danielinteractive yes, I was using the `tern.mmrm@main` with `staged.dependencies`.

**Comment by juliadedic1** [comment]
@danielinteractive ran in BEE and tests are passing. Also looking at NEST - integration test status chat, looks like tests are passing. 
![image](https://user-images.githubusercontent.com/99106549/206022001-d3e86636-a38f-4753-a45c-a13679f7c0d2.png)

**Comment by danielinteractive** [comment]
@arkadiuszbeer can you confirm that this resolved itself?

**Comment by danielinteractive** [comment]
I think this resolved automatically because we switched to the CRAN version of `mmrm`. In the github version we deprecated a function with a warning in `mmrm` which was likely the reason for this. So closing this one and making a new issue.

**Comment by arkadiuszbeer** [comment]
@danielinteractive yes, I can confirm that this is resolved (test on BEE, integration tests on dockers and GRAN are passing).
