### ISSUE TITLE
cran release v0.3.0

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern.mmrm#147]
- [x] Align to the latest mmrm
- [x] https://github.com/insightsengineering/tern.mmrm/issues/152
- [x] https://github.com/insightsengineering/tern.mmrm/issues/156
- [x]  Update README and NEWS.md
- [x]  create cran_releae_0.3.0_branch
- [x]  update DESCRIPTION
- [x] remove Remotes field from DESCRIPTION
- [x]  Submission to CRAN
- [x]  Address any CRAN feedback
- [x]  Acceptance on CRAN
- [x]  tag v0.3.0
- [x]  merge cran_releae_0.3.0_branch

**Comment by danielinteractive** [comment]
Thanks @shajoezhu for starting this, I think I can help from maintainer / mmrm side on this in the next weeks. We will have a new mmrm CRAN release soon, and this would be good to sync with that, and we will need downstream updates here

**Comment by danielinteractive** [comment]
This should be ready to start now. Once the new `mmrm` arrives on CRAN it could then be submitted to CRAN.

**Comment by danielinteractive** [comment]
Can be closed?
