### ISSUE TITLE
r-universe: R CMD CHECK note

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/tern.mmrm#200]
```
* checking package dependencies ... NOTE
Package suggested but not available for checking: 'maditr'
```

[Build and deploy / Build R-oldrel for Windows](https://github.com/r-universe/pharmaverse/actions/runs/12044578814/job/33581873653#logs)
[Build and deploy / Build R-oldrel for MacOS](https://github.com/r-universe/pharmaverse/actions/runs/12044578814/job/33581873785#logs)

**Comment by shajoezhu** [comment]
https://cran.r-project.org/web/checks/check_results_maditr.html
https://cran.r-project.org/web/checks/check_results_tern.mmrm.html

they look ok there? is this a r-universe bug?

**Comment by shajoezhu** [comment]
they look ok now. not an issue any more
