### ISSUE TITLE
Add baseline rows to MMRM LS means table on top

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/tern.mmrm#52]
Idea:
![image](https://user-images.githubusercontent.com/1071227/166700863-9eb0db10-3844-4126-b685-0568a064bb38.png)

See [docs.roche.com/doc/tlg-catalog/2022_01_28/tlg_catalog/tables/mmrmt01](https://docs.roche.com/doc/tlg-catalog/2022_01_28/tlg_catalog/tables/mmrmt01/) 

To do:

- [x] Finish design doc here
- [x] Afterwards make a corresponding branch / PR for TLG catalog to add as section 1.3 in template MMRMT01
  - [x] clone https://code.roche.com/nest/docs/tlg-catalog/devel
  - [x] formally this will be closing then https://code.roche.com/nest/docs/tlg-catalog/devel/-/issues/127

**Comment by juliadedic1** [comment]
Added PR here: https://code.roche.com/nest/docs/tlg-catalog/devel/-/merge_requests/94

**Comment by danielinteractive** [comment]
thanks @juliadedic1 , just reviewed already :-)

**Comment by danielinteractive** [comment]
@juliadedic1 added comments in https://code.roche.com/nest/docs/tlg-catalog/devel/-/merge_requests/94
