### ISSUE TITLE
[Question]: Were you able to bypass the lme4 limitations and make it GLS-compliant for the MMRM?

### ISSUE THREAD

**Issue by Generalized** [insightsengineering/tern.mmrm#82]
### What is your question?

I noticed that the procedure here is based on lme4.

Lme4 couldn't handle the real MMRM models (fixed-effect only) natively for the entire period I checked it and did not allow me to specify the structure of the residual covariance matrix. This way, it couldn't truly model compound symmetry (it is not equivalent to random intercept model in general, for not allowing for negative correlations - it zeros them) or unstructured covariance, only approximate estimates, which might differ from reality noticeably from the marginal model.

The two approaches, R-side and G-side, resulting in marginal and conditional model respectively, however have similar interpretation for the general linear model, are different in logic on handling the within-subject/cluster covariances, because the R and G-side contribute to the final var-cov matrix in a way different manner. They complement each other (summed together), but in the MMRM we use only the R-side, which gives enough flexibility without the need to apply tricks to approximate / mimic the R-side with random effects. 

Sometimes certain var-cov can be achieved with G, but that's very limited mainly to independence or "semi-compound-symmetry". What is worse, using a mixed model forces the user to verify appropriate statistical assumptions about the random effects, adding unnecessary complications. Also, mixed models are sensitive to model misspecification (we have two parts: fixed and random), so unless we use the unstructured covariance structure, there was a strong need for robust (empirical) standard errors rather than the model-ones. 

That's why the MMRM was advised for decades rather than mixed models to not focus on random effects, but rather to flexibly specify the residual covariances over time, by pushing all (known or unknown) sources of variability together into the residual covariance. This exactly property addressed the problem with the random part misspecification. Currently it seems that the SAS "repeated" approach in prox mixed or glimmix (according the manual it's done via GLS) could be reproduced only by the nlme::gls(), offering the marginal fixed-only model with numerous covariance structures, which fits the definition of MMRM. 

/ The emmeans gives the Satterthwaite DF for it, both via analytical formula (according to the author, taken from the pkbkrtest code), or numerical approximation the default fails to calculate. I'm still testing the numerical validity of it. /

Now, my question is:  were you able to bypass these limitations of lme4, so now it can truly resign from incorporating random effects to the model and entirely specify the model via R matrix with all the main covariance structures, for example available in nlme::gls() or glmmTMB?

I noticed additional project on that, which employs the glmmTMB, which seems to allow one to specify the residual covariance structure: https://github.com/openpharma/mmrm
Are the two kind of "competitors" or rather experiment which one will perform better?

https://openpharma.github.io/mmrm/main/articles/algorithm.html

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by danielinteractive** [comment]
Hi @Generalized , we completely refactored `tern.mmrm` now so that it no longer relies on `lme4` but instead uses the new `mmrm` package that you noted. See `mmrm` for details on the model fitting etc, but this is really using a non-random effects model now.
